# Generated by Django 6.0.3 on 2026-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_goals_playerweekdetails_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekdetails',
            name='week_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_year',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
