# Generated by Django 6.0.3 on 2026-04-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_playerweekdetails_week_name_alter_month_month_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], max_length=100)),
                ('home_score', models.IntegerField(default=0, null=True)),
                ('away_score', models.IntegerField(default=0, null=True)),
                ('completion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1_score',
            new_name='goal_cancel',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_score',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_label',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Player', 'Player'), ('League', 'League'), ('Injury', 'Injury'), ('Transfer', 'Transfer')], max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.playermatch'),
        ),
    ]
